# auto write a latex table with Ohm break even date and days from today 
# until then. 
import numpy as np
import pandas as pd

# read data:
df = pd.read_excel(
    "bin/break-even-dates.xlsx",
    index_col=[0],
    parse_dates=True,
    )

# define table:
table_header = """%
% This table was autogenerated by write-latex-table.py. 
%
\\begin{longtable}[c]{ l c c c }
\caption{Simplyrangel's Ohm break even price points. Based on 2.6 Ohm purchased at 293.97USD/Ohm basis. Calculated 2022-01-23.} \\\\
\hline
\\textbf{rate type} & \\textbf{break even date} & \\textbf{days until} & \\textbf{accrued Ohms} \\\\
\hline
"""

# define rate names:
rate_masks = {
    "best_case_rates": "OIP-63 best case",
    "uniform_distr_rates": "OIP-63 uniform distr.",
    "worst_case_rates": "OIP-63 worst case",    
    } 

# write latex file:
with open("break-even-table.tex","w") as of:
    of.write(table_header)
    for c0,c1,c2,c3 in zip(
        df.index,
        df.breakeven_date,
        df.days_until,
        df.ohms,
        ):
        row = "%s & %s & %d & %.2f \\\\ \n" %(
            rate_masks[c0],
            c1.strftime("%b %d, %Y"),
            c2,
            c3,
            )
        of.write(row)
    of.write("\hline")
    of.write("\end{longtable}")
    
